<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root [
	<!ELEMENT root (total,category,category,category)>
	<!ATTLIST root id ID #REQUIRED>

	<!ELEMENT category (label,total,year*)>
	<!ATTLIST category id ID #REQUIRED>

	<!ELEMENT label (#PCDATA)>
	<!ATTLIST label id ID #REQUIRED>

	<!ELEMENT year (total,month+)>
	<!ATTLIST year id ID #REQUIRED>

	<!ELEMENT month (total,day+)>
	<!ATTLIST month id ID #REQUIRED>

	<!ELEMENT day (total,entry+)>
	<!ATTLIST day id ID #REQUIRED>

	<!ELEMENT entry (amount,description,timestamp)>
	<!ATTLIST entry id ID #REQUIRED>

	<!ELEMENT amount (#PCDATA)>
	<!ATTLIST amount id ID #REQUIRED>

	<!ELEMENT description (#PCDATA)>
	<!ATTLIST description id ID #REQUIRED>

	<!ELEMENT timestamp (#PCDATA)>
	<!ATTLIST timestamp id ID #REQUIRED>

	<!ELEMENT total (#PCDATA)>
	<!ATTLIST total id ID #REQUIRED>
	]>
<root id="r"><total id="t">0.00</total><category id="c-1"><label id="c-1-l">Food</label><total id="c-1-t">0.00</total></category><category id="c-2"><label id="c-2-l">Entertainment</label><total id="c-2-t">0.00</total></category><category id="c-3"><label id="c-3-l">Transportation</label><total id="c-3-t">0.00</total></category></root>